spring.application.name=springai-rag-isupport-demo

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.embeddings.options.model=text-embedding-3-small
spring.ai.retry.enabled=true

spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.initialize-schema=false


app.ingestion.chunk-size=500
app.ingestion.inbox-folder=file:./pdf-inbox
app.ingestion.default-user-id=system
app.ingestion.pages-per-document=1

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:init/schema.sql

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
